-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, CONCAT(CITY,' ',STREET_ADDRESS1, ' ',STREET_ADDRESS2) AS 전체주소, 
CONCAT(SUBSTR(TLNO,1,3),'-',CONCAT(SUBSTR(TLNO,4,4)),'-',CONCAT(SUBSTR(TLNO,8,4))) AS 전화번호
FROM USED_GOODS_USER U JOIN 
(
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
) AS B
ON U.USER_ID = B.WRITER_ID
ORDER BY USER_ID DESC;
                                  