-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/',BOARD_ID,'/',FILE_ID, FILE_NAME, FILE_EXT) FILE_PATH
# 첨부파일 경로
FROM (SELECT * FROM USED_GOODS_FILE ORDER BY FILE_ID DESC) AS USF
WHERE BOARD_ID = (
    SELECT BOARD_ID FROM USED_GOODS_BOARD
    WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
);